<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Microsoft.Azure.Functions.Extensions.HelloWorld</AssemblyName>
    <Description>Hello World extension for Azure Functions - A sample extension for new extension authors</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.45" />
  </ItemGroup>

</Project>
