variables:
  - name: configuration
    value: Release
  - name: project
    value: Microsoft.Azure.Functions.Extensions.HelloWorld.sln
  - name: Build.Counter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 0)]
  - name: RepoRoot
    value: $(Build.SourcesDirectory)
