parameters:
  - name: publishToNugetOrg
    displayName: Publish to nuget.org?
    type: boolean
    default: false

pr: none
trigger: none

resources:
  pipelines:
    - pipeline: build
      source: helloworld-extension.official

extends:
  template: /eng/ci/templates/jobs/release-packages-host.yml@self
  parameters:
    publishToNugetOrg: ${{ parameters.publishToNugetOrg }}
