parameters:
  - name: createArtifacts
    type: boolean
    default: true

jobs:
  - job: BuildArtifacts
    displayName: Build Artifacts

    variables:
      - template: /eng/ci/templates/variables/build.yml@self
      - name: packages_path
        value: $(Build.ArtifactStagingDirectory)/packages

    templateContext:
      outputParentDirectory: $(packages_path)
      outputs:
        - ${{ if eq(parameters.createArtifacts, true) }}:
            - output: pipelineArtifact
              displayName: Publish artifacts
              path: $(packages_path)
              artifact: drop

    steps:
      - task: NuGetAuthenticate@1
        displayName: 'NuGet Authenticate'

      - task: UseDotNet@2 # The pinned SDK we use to build
        displayName: Install .NET SDK from global.json
        inputs:
          packageType: sdk
          useGlobalJson: true

      - task: DotNetCoreCLI@2
        displayName: Build project
        inputs:
          command: custom
          custom: build
          arguments: -c $(configuration)
          projects: $(project)

      - pwsh: |
          Write-Host "===== dotnet --info ====="
          dotnet --info

          Write-Host ""
          Write-Host "===== Installed SDKs ====="
          dotnet --list-sdks

          Write-Host ""
          Write-Host "===== Installed Runtimes ====="
          dotnet --list-runtimes
        displayName: 'Display .NET info'

      - task: DotNetCoreCLI@2
        displayName: Run tests
        inputs:
          command: test
          arguments: --no-build -c $(configuration)
          projects: $(project)

      - ${{ if eq(parameters.createArtifacts, true) }}:
          - template: ci/sign-files.yml@eng
            parameters:
              displayName: Sign worker extension assemblies
              folderPath: out/bin/Worker.Extensions.HelloWorld/
              pattern: Microsoft.Azure.Functions.Worker.Extensions.HelloWorld.dll
              signType: dll

          - task: DeleteFiles@1
            displayName: Delete CodeSignSummary files
            inputs:
              sourceFolder: out/bin/Worker.Extensions.HelloWorld/
              contents: '**/CodeSignSummary-*.md'

          - template: ci/sign-files.yml@eng
            parameters:
              displayName: Sign host extension assemblies
              folderPath: out/bin/Extensions.HelloWorld/
              pattern: Microsoft.Azure.Functions.Extensions.HelloWorld.dll
              signType: dll

          - task: DeleteFiles@1
            displayName: Delete CodeSignSummary files
            inputs:
              sourceFolder: out/bin/Extensions.HelloWorld/
              contents: '**/CodeSignSummary-*.md'

          - task: DotNetCoreCLI@2
            displayName: 'Build package'
            inputs:
              command: custom
              custom: pack
              arguments: --no-build -c $(configuration) -o $(packages_path)
              projects: $(project)

          - template: ci/sign-files.yml@eng
            parameters:
              displayName: Sign nuget packages
              folderPath: $(packages_path)
              pattern: '*.nupkg'
              signType: nuget

          - task: DeleteFiles@1
            displayName: Delete CodeSignSummary files
            inputs:
              sourceFolder: $(packages_path)
              contents: '**/CodeSignSummary-*.md'
